version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.DEV
    # Mount the current directory into `/code` inside the running container.
    volumes:
      - .:/code
